export const USER_LIST_REQUESTED = 'USER_LIST_REQUESTED'
export const USER_LIST_RECEIEVED = 'USER_LIST_RECEIEVED'
export const SEARCH_USER_REQUESTED = 'SEARCH_USER_REQUESTED'
export const SEARCH_USER_RECEIEVED = 'SEARCH_USER_RECEIEVED'